name: Android CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_distribute:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Set up Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: login:ci

      - name: Archive APK
        uses: actions/upload-artifact@v2
        with:
          name: Release APK
          path: app/build/outputs/apk/release/app-release.apk

  distribute:
    needs: build_and_distribute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Firebase CLI
        uses: w9jds/firebase-action@master
        with:
          args: login:ci

      - name: Download APK Artifact
        uses: actions/download-artifact@v2
        with:
          name: Release APK

      - name: Upload to Firebase Distribution
        run: firebase appdistribution:distribute app-release.apk --app <YOUR_FIREBASE_APP_ID> --release-notes "New release build" --groups internal